services:
  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    container_name: homarr

    restart: unless-stopped

    ports:
      - "7575:7575"

    env_file:
      - .env

    volumes:
      - /srv/data/homarr:/appdata
