name: homarr

services:
  homarr:
    image: ${IMAGE}:${IMAGE_TAG}
    container_name: ${CONTAINER_NAME}

    restart: unless-stopped

    ports:
      - "7575:7575"

    env_file:
      - /srv/data/homarr/.env

    volumes:
      - /srv/data/homarr:/appdata

    networks:
      - subicloud

networks:
  subicloud:
    external: true
