name: caddy

services:
  caddy:
    image: caddy:2

    container_name: caddy

    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /srv/data/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - /srv/data/caddy/data:/data
      - /srv/data/caddy/config:/config

    networks:
      - subicloud

networks:
  subicloud:
    external: true
