name: caddy

services:
  caddy:
    image: ${IMAGE}:${IMAGE_TAG}

    container_name: ${CONTAINER_NAME}

    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./config:/etc/caddy:ro
      - /srv/data/caddy/data:/data
      - /srv/data/caddy/config:/config

    networks:
      - subicloud

networks:
  subicloud:
    external: true
