name: glances

services:
  glances:
    image: ${IMAGE}:${IMAGE_TAG}

    container_name: ${CONTAINER_NAME}

    restart: unless-stopped

    pid: host

    privileged: true

    environment:
      - GLANCES_OPT

    ports:
      - "61208:61208"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro

    networks:
      default:
        aliases:
          - glances

networks:
  default:
    name: ${NETWORK_NAME}
    external: true